### ISSUE TITLE
Binary Arithmetic in the TypeScript Type System Bug

### ISSUE THREAD

**Issue by krzysztof-grzybek** [JoshuaKGoldberg/Goldblog#27]
Hi Joshua! Thank You for awesome article about binary arithmetic in Typescript Type System. It was a really interesting read!
However, I think there's one issue in the final code. Take a look [here](http://www.typescriptlang.org/play/?ssl=39&ssc=88&pln=33&pc=1#code/C4TwDgpgBAQglsKBeKAGKAfKBGA3AKH1EigEkA7YADmSgG15gAaWBFx9t157znxgLoEi4aIwCCAE0kAecVAgAPYBHKSAzr1gLlqjdwB8yfFFP1x7ATpVrNdVC1RWA-PQdorALhNm6F2FZKNvp02I5WWPYs2C70YR5Q3mZu0QI+wsRiCFIactZ6mhTU7Pm2ZJRURigA3j6mdAAKUHDkaJg47QBM7QDM7QAs7QCs7QBs7QDsAp7cOXKNAuwLBgQAvhmis9IAKgAWAE4QEHlBBVowpfocUADCl5qMVXXm7Cw3gbplUWjhUK7fTkSzz8r1uH2Cdni7kBkXcUIiKR+OFioV+SV8-hgb3BZ1ROF+kShqXa33iMT+iPJ6PqZLSpg2JCKVDmz3kpzKTKYzwu7P0nMIyQA9ILbgB7AA24ogAGNEHQAMoAVwAtm8AIb7fYgASaUUAM2a5DAisQTPUrOkEEk9y2uUxVVt6jk7AMXOewqge2gh3UivFwAA5Jo9XB9upEAAjBDNTTAXbQENhxBK5Ws4DoXmaHJW+xWFDZyS5t1CkVeqA+v2INWICBq6W7Q2SJQxqBx6ApqB6-ai5Wt3bVxvNgDUfegYEOADc4KLFZobhqtQA6NPYG0SHYHI7zGJLHdQAu50ICB3ryR7Q7HcRH3eLfeWwtOI+utPdTO289bq+dW8wOjflgHjET60KeH6Xn+P4QQB95Hk+XLJOIwB9G+oGbuBPSQRh0FNoW37ASgqEXvMWGwHQJEHnhMTPghwCDCh2QbkRV79JBLHYTmGH4e+aHzGxpF8QenFUfBZiISM9HADkYHzEMkGyexhYsVxhGfnQ8mkepB5KcJabjBJUk8VeoyQcZClqQIykMWehl0KZpF2QeslwWmExrlZ0lXlMSxeXeOG2RZVEge5Nk+b+PkHsZzmmA6fjpkW+7ANg8WIZ0yVIWl-RpUMaWjGlEy5kIhCZFAAAkcYXrQeJEki0KOOEBDFSVIYTtAKB4nCdU1Z1TgMtAJUQHAADmuyICgTJzGVaEsE1cAtSshDSqK5DhgoQ0jTM-VraNiK1fiXU1YVQA). I think it can be fixed simply like [this](http://www.typescriptlang.org/play/#code/C4TwDgpgBAQglsKBeKAGKAfKBGA3AKH1EigEkA7YADmSgG15gAaWBFx9t157znxgLoEi4aIwCCAE0kAecVAgAPYBHKSAzr1gLlqjdwB8yfFFP1x7ATpVrNdVC1RWA-PQdorALhNm6F2FZKNvp02I5WWPYs2C70YR5Q3mZu0QI+wsRiCFIactZ6mhTU7Pm2ZJRURigA3j6mdAAKUHDkaJg47QBM7QDM7QAs7QCs7QBs7QDsAp7cOXKNAuwLBgQAvhmis9IAKgAWAE4QEHlBBVowpfocUADCl5qMVXXm7Cw3gbplUWjhUK7fTkSzz8r1uH2Cdni7kBkXcUIiKR+OFioV+SV8-hgb3BZ1ROF+kShqXa33iMT+iPJ6PqZLSpg2JCKVDmz3kpzKTKYzwu7P0nMIyQA9ILbgB7AA24ogAGNEHQAMoAVwAtm8AIb7fYgASaUUAM2a5DAisQTPUrOkEEk9y2uUxVVt6jk7AMXOewqge2gh3UivFwAA5Jo9XB9upEAAjBDNTTAXbQENhxBK5Ws4DoXmaHJW+xWFDZyS5t1CkVeqA+v2INWICBq6W7Q2SJQxqBx6ApqB6-ai5Wt3bVxvNgDUfegYEOADc4KLFZobhqtQA6NPYG0SHYHI7zGJLHdQAu50ICB3ryR7Q7HcRH3eLffpo+utPdTO289bq+dW8wOiflgHmIPrQp5vpeP5fmBf7ANgD5csk4jAH0L7AZuoE9OBaF-pahafoBKDIRe8wYbAdBEfBnQwWmgxIdkG4EVe-TgQxmFNoWaG4a+KHzExxHcfBPQUXBwAjNRwA5CB8xDOBknMTmDHsfh750NJxHKfB-QCWY8HjCJYmcVeozgQZMmFpJ8k0Weel0EZxHWfBQwaaY8ETGu5niVeUxLB5+5YVZAhmaJtGKV535eVpGkOn495OJB0HRXe5FxXxRZ3upiVCclYVpRMuZCIQmRQAAJHGF60HiRJItCjjhAQ+UFSGE7QCgeJwlVFWtU4DLQAVEBwAA5rsiAoEycxFShLB1XADUrIQ0qiuQ4YKH1A0zN1S2DYilX4m1FW5UAA) (take a look at the last argument of `BitAddThree`).

I just wanted to point that out because some astute readers might be scratching their heads why it doesn't work for this case :D 
Again, thanks for the really awesome article, cheers!

**Comment by JoshuaKGoldberg** [comment]
Ha, great catch - thanks @krzysztof-grzybek! I'll fix that right away.
