### ISSUE TITLE
RSS feed isn't correct

### ISSUE THREAD

**Issue by Pinjasaur** [JoshuaKGoldberg/Goldblog#391]
hi Josh! I tried to add your blog's RSS feed to my feed reader and found some issues to address:

https://blog.joshuakgoldberg.com/rss.xml _does_ exist, but has some problems:

1. it doesn't have recent content
2. the encoding and/or formatting doesn't seem correct(?)

	- <img width="673" alt="image" src="https://github.com/JoshuaKGoldberg/Goldblog/assets/6335792/65bc518d-5cab-4b9c-ae21-48cd5e369dfa">
	- (latest Firefox)
	- <img width="713" alt="image" src="https://github.com/JoshuaKGoldberg/Goldblog/assets/6335792/7c4483ce-2a5c-4ab1-adcf-b1049f171d1c">
	- (notice the tell-tale `&gt;`-style encoding)

I'm not terribly familiar with Gatsby but it seems like there's a pretty reasonable out-of-the-box solution: https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-an-rss-feed/

I might see if I can take a stab at a PR to fix this. But regardless, wanted to let you know. :)

P.S. Your learningtypescript.com book looks excellent, nice work!

**Comment by Pinjasaur** [comment]
Following up that I think my complaint about the `&gt;` and `&lt;` was invalid—that's just the encoded content of the actual post contents. Didn't dig into the "not well-formed" error but oh well, it's probably fine-enough-for-now.

**Comment by JoshuaKGoldberg** [comment]
Ah thanks for filing @Pinjasaur! This has been a pain in the butt for a while 😂. I'm in the late stages of migrating the blog to my new personal site: https://github.com/JoshuaKGoldberg/joshuakgoldberg-dot-com-next/pull/26

But if you want to send a PR (aka: I see the PR, thanks for sending!) that works too in the meantime! ❤️
